### ISSUE TITLE
How to add support for a new target to Rust

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust-forge#17]
As in what needs to be done to be able to compile programs for the target using `rustc` / Cargo and what needs to be done to have binary releases of std, rustc and Cargo for the target.

I just gave a detailed answer about that [here](https://www.reddit.com/r/rust/comments/5ag60z/how_do_i_bootstrap_rust_to_crosscompile_for_a_new/d9gdjwf/). We should add that documentation here so I can just point people to it in the future.

cc @brson

**Comment by sanxiyn** [comment]
The comment omits writing `cabi_*.rs` file which is necessary for porting to new architectures.

**Comment by japaric** [comment]
@sanxiyn That comment is certainly not comprehensive. I'll send a PR with more complete documentation when I find the time.

**Comment by Issue-Hsu** [comment]
@japaric Thanks for your previous answer. Do you still go on the complete documentation for adding new target support to Rust? Any document about the interfaces between Rust and LLVM?
Thanks!

**Comment by japaric** [comment]
> Do you still go on the complete documentation for adding new target support to Rust?

Nope, sorry. At one point I was writing some documentation but it was rather boring and the intended audience seemed rather small so I dropped it.

> Any document about the interfaces between Rust and LLVM?

There are none other than the source code. But apart from what's mention in the reddit link and the cabi mentioned above I think there's nothing else to worry about when adding a new target / architecture. (There are other places where rustc relies on LLVM, like debuginfo, but it does so in a architecture agnostic way so there's nothing to change in rustc to support a new architecture)

I think the best documentation, right now, for adding a new target, apart from the reddit link above, are the other PRs sent to rust-lang/rust to add new targets.

**Comment by XAMPPRocky** [comment]
@japaric Thank you for your issue, is the answer you link in the original post still relevant today? If so I can make a PR adding it to the Rust Forge.

**Comment by sanxiyn** [comment]
Note: `cabi_*.rs` is now under `librustc_target/abi/call`.

**Comment by XAMPPRocky** [comment]
I'm going to close this in favour of the ongoing discussion in the [Target Tier Policy](https://github.com/rust-lang/rfcs/pull/2803)
