### ISSUE TITLE
Are thumb* targets really Tier 2?

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust-forge#177]
thumbv6m-none-eabi, thumbv7m-none-eabi, thumbv7em-none-eabi, and thumbv7em-none-eabihf are currently listed as Tier 3 in https://forge.rust-lang.org/platform-support.html.

> Tier 3 platforms are those which the Rust codebase has support for, but which are not built or tested automatically, and may not work. Official builds are not available.

However, libcore for these targets *is* built on CI (see `src/ci/docker/dist-various-1/Dockerfile`), and are available through rustup (see `rustup target list | grep thumb`). This sounds like the description of Tier 2.

Should the forge be updated to match reality?

CC @alexcrichton, @japaric

**Comment by alexcrichton** [comment]
Indeed many of these have been promoted recently!
