### ISSUE TITLE
forge.rust-lang.org doesn't have the newest 2018 Rust release 1.31.0

### ISSUE THREAD

**Issue by willi-kappler** [rust-lang/rust-forge#179]
# Content Bug Report
Those who can't use rustup have to download it from the rustforge webpage: "Standalone installers".
Unfortunately that page doesn't show the newest stable release 1.31.0.

## Page(s) Affected
https://forge.rust-lang.org/other-installation-methods.html#standalone

## What needs to be fixed?
Update the URLs.

## Suggested Improvement
Replace rust-1.30.1 with rust-1.31.0 in the file names, at least it worked for the linux tar ball that I needed.

**Comment by willi-kappler** [comment]
Ah sorry, didn't know that. I just followed the link from the new web page. Thanks for transferring it!

**Comment by pietroalbini** [comment]
Updated all the links. Thanks for pointing this out!

**Comment by willi-kappler** [comment]
Perfect, thanks!
