### ISSUE TITLE
The target list is missing targets/is outdated

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust-forge#186]
Looking at the [actual list of targets supported](https://github.com/rust-lang/rust/tree/master/src/librustc_target/spec) it is fairly clear that the list is not exhaustive.

Notable examples: armv4, riscv32...

**Comment by sanmai-NL** [comment]
`rust-nightly-x86_64-unknown-linux-musl` is also missing.

**Comment by jdm** [comment]
Windows arm64 is also missing.
