### ISSUE TITLE
"Other Installation Methods" out of date

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust-forge#191]
_Note: this was initially opened on https://github.com/rust-lang/www.rust-lang.org/issues/688 by @njaard_

# Content Bug Report

## Page(s) Affected

The links on https://forge.rust-lang.org/other-installation-methods.html#standalone only show downloads for the 1.31.0 release.

## What needs to be fixed?
It should always be updated at the same time as the front page gets updated to show the latest release.

**Comment by pietroalbini** [comment]
Should be up to date now.

**Comment by yoshuawuyts** [comment]
@pietroalbini thanks for fixing this! :tada:

**Comment by pietroalbini** [comment]
You should thank @Centril for it!
