### ISSUE TITLE
Target list out of date/core-only builds

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust-forge#198]
I recently found out that Rust ships core-only builds from some targets. That this is even an option is not at all clear from the platform support page. This applies to at least the following targets (which aren't even mentioned):

* riscv32imac-unknown-none-elf
* riscv32imc-unknown-none-elf

**Comment by Disasm** [comment]
Other missing targets:
* aarch64-pc-windows-msvc (tier1?)
* armv5te-unknown-linux-musleabi (tier1?)
* armebv7r-none-eabi
* armebv7r-none-eabihf
* armv7r-none-eabi
* armv7r-none-eabihf
* thumbv6m-none-eabi
* thumbv7em-none-eabi
* thumbv7em-none-eabihf
* thumbv7m-none-eabi

I think that `-none-` targets are core-only too, but I'm not sure about it.

cc @japaric

**Comment by japaric** [comment]
The 4 thumb targets are core-only and are listed under tier 3 https://github.com/rust-lang/rust-forge/blob/master/platform-support.md#tier-3 though they are now effectively tier 1 as PRs are gated on builds of core and QEMU tests passing.
