### ISSUE TITLE
"Other Installation Methods" out of date

### ISSUE THREAD

**Issue by njaard** [rust-lang/rust-forge#205]
# Content Bug Report

## Page(s) Affected

The links on https://forge.rust-lang.org/other-installation-methods.html#standalone only show downloads for the 1.32.0 release.

# What needs to be fixed?

It should always be updated at the same time as the front page gets updated to show the latest release.

Simply fixing the page to show the latest version isn't a fix to this report. A fix to this report is that the latest version always appears when there is a new version.

**Comment by pietroalbini** [comment]
I updated the data manually, but unfortunately it's not easy to automatically update the data here. I'm thinking of a way to move this to the main website again.
