### ISSUE TITLE
Offer zip builds

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust-forge#225]
If you go here:

http://forge.rust-lang.org/other-installation-methods#standalone-installers

you see MSI and TAR.GZ installers for Windows. This is strange because typically
programming language vendors will offer:

1. MSI or EXE installer
2. ZIP file with compiler or interpreter that can be extracted and run

the Rust TAR.GZ is similar to option 2, but if you extract `rustc.exe` wont
actually run because even with the TAR.GZ it has to be extracted and installed
before `rustc.exe` is usuable. This contrasts with other programming languages that offer both an executable installer and ZIP files that can be extracted and run. For example Go:

https://golang.org/dl

and Nim:

https://nim-lang.org/install_windows.html

Python:

https://python.org/downloads/release/python-373

and C#:

https://dotnet.microsoft.com/download/dotnet-core/2.2

PHP:

https://windows.php.net/download

Perl:

http://strawberryperl.com/releases.html

**Comment by cup** [comment]
https://github.com/rust-lang/www.rust-lang.org/issues/770

**Comment by cup** [comment]
https://github.com/rust-lang/rust/issues/60335

**Comment by cup** [comment]
https://github.com/rust-lang/rustup.rs/issues/1851

**Comment by ehuss** [comment]
Closing/moving to https://github.com/rust-lang/rust/issues/116028, since this website doesn't control which release installers are published.
