### ISSUE TITLE
Add icons for stable, beta and nightly

### ISSUE THREAD

**Issue by chocol4te** [rust-lang/rust-forge#237]
I was thinking of something [similar to Firefox channels](https://www.mozilla.org/en-US/firefox/channel/desktop/).

[What Rust is it?](https://www.whatrustisit.com) already does this for beta, it would be nice for Rust Forge to have the same, with the addition of a nightly-specific logo.

I'd be happy to try and make the icons, but I wanted to know whether this is desired by anyone else.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! The creation of an official nightly Rust logo is something that is bigger than the scope of the Rust forge. I think just putting a nightly badge similar to the beta thing would be fine though. I've made a sample what that could look like with Firefox Aurora colours.
![rust-logo-blk-nightly](https://user-images.githubusercontent.com/4464295/61170822-f6604280-a56e-11e9-9d34-40ffba49225a.png)

**Comment by XAMPPRocky** [comment]
This issue isn't relevant anymore as the layout of the channels is now a plain table instead of a three column list, so logos aren't really needed to fill the whitespace anymore.
