### ISSUE TITLE
Document tier 3 platform support

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/rust-forge#255]
### [Tier 3 platforms](https://forge.rust-lang.org/release/platform-support.html#tier-3)

This is a tracking issue for adding documentation on the level of support a tier 3 Rust toolchain has. This is mainly "Can I use std on that platform?", "Can I build and run rustc on that platform?", and "Can I can build and run Cargo on that platform?".

- [x] `aarch64-unknown-freebsd`
- [ ] `aarch64-unknown-hermit`
- [ ] `aarch64-unknown-netbsd`
- [x] `aarch64-unknown-none`
- [x] `aarch64-unknown-redox`
- [ ] `aarch64-uwp-windows-msvc`
- [ ] `aarch64-wrs-vxworks`
- [ ] `armv4t-unknown-linux-gnueabi`
- [x] `armv6-unknown-freebsd`
- [ ] `armv6-unknown-netbsd-eabihf`
- [x] `armv7-unknown-freebsd`
- [ ] `armv7-unknown-netbsd-eabihf`
- [ ] `armv7-wrs-vxworks-eabihf`
- [ ] `hexagon-unknown-linux-musl`
- [ ] `i686-unknown-dragonfly`
- [x] `i686-uwp-windows-gnu`
- [x] `i686-uwp-windows-msvc`
- [ ] `i686-wrs-vxworks`
- [x] `mips64-unknown-linux-muslabi64`
- [x] `mips64el-unknown-linux-muslabi64`
- [ ] `mipsisa32r6-unknown-linux-gnu`
- [ ] `mipsisa32r6el-unknown-linux-gnu`
- [ ] `mipsisa64r6-unknown-linux-gnuabi64`
- [ ] `mipsisa64r6el-unknown-linux-gnuabi64`
- [ ] `powerpc-unknown-linux-musl`
- [ ] `powerpc-unknown-netbsd`
- [ ] `powerpc-wrs-vxworks`
- [ ] `powerpc-wrs-vxworks-spe`
- [ ] `powerpc64-unknown-freebsd`
- [ ] `powerpc64-unknown-linux-musl`
- [ ] `powerpc64-wrs-vxworks`
- [ ] `powerpc64le-unknown-linux-musl`
- [ ] `riscv32i-unknown-none-elf`
- [ ] `sparc64-unknown-openbsd`
- [ ] `thumbv7a-pc-windows-msvc`
- [x] `wasm32-experimental-emscripten`
- [ ] `x86_64-pc-solaris`
- [ ] `x86_64-unknown-hermit`
- [ ] `x86_64-unknown-l4re-uclibc`
- [ ] `x86_64-unknown-uefi`
- [ ] `x86_64-wrs-vxworks`

**Comment by jonas-schievink** [comment]
The thumbv8 targets are all shipped in rustup by the way, so they should probably be moved to tier 2

**Comment by jonas-schievink** [comment]
Yup, opened https://github.com/rust-lang/rust-forge/issues/346 for that

**Comment by flying-sheep** [comment]
`avr-unknown-unknown` has been enabled: rust-lang/rust#69478

**Comment by XAMPPRocky** [comment]
@flying-sheep Would you be willing to make a PR adding it?

**Comment by flying-sheep** [comment]
Actually I don’t even know what the checkmarks on the [platform support page](https://forge.rust-lang.org/release/platform-support.html) mean. That you can compile those things there? That there’s binary distributions of those things?

Also does something other than the platform support page need to be changed?

**Comment by yerke** [comment]
@XAMPPRocky Opened a draft https://github.com/rust-lang/rust-forge/pull/380

**Comment by XAMPPRocky** [comment]
@flying-sheep A check means that you can build and compile that component for that architecture and it will work. So if something has ticked std and rustc, it means you can build std and rustc for that platform. It’s probably not the most clear currently.

**Comment by flying-sheep** [comment]
Hmm, “The columns below indicate whether the corresponding component works on the specified platform” is sufficient information, but yeah, I think a bit more clarification wouldn’t hurt.

**Comment by sajattack** [comment]
I noticed `mipsel-sony-psp` is missing from this list.

**Comment by ehuss** [comment]
I'm going to close since the platform support is no longer documented here. This is being tracked at https://github.com/rust-lang/rust/issues/113739 and https://github.com/rust-lang/rust/pull/116004.
