### ISSUE TITLE
Document release tarballs with vendor directories filled.

### ISSUE THREAD

**Issue by andrewchambers** [rust-lang/rust-forge#258]
It has come to my attention there doesn't seem to be a way to download rust release tarballs which have dependencies vendored and submodules cloned.

The stable link here: https://forge.rust-lang.org/infra/other-installation-methods.html gives a 404 error.

The github release tarballs don't have dependencies bundled.

**Comment by andrewchambers** [comment]
@Mark-Simulacrum ah, I see the link. I'm slightly concerned this ticket will just be ignored similar to other forge tickets on the same topic.

**Comment by andrewchambers** [comment]
see https://github.com/rust-lang/rust-forge/issues/215

**Comment by andrewchambers** [comment]
@Mark-Simulacrum Note the links you provided don't have vendor directories and submodules filled.

**Comment by Mark-Simulacrum** [comment]
Hm, that looks false to me? Unpacking https://static.rust-lang.org/dist/2019-08-15/rustc-1.37.0-src.tar.xz I see a vendor directory with all the crates.io deps and a quick `ls src/llvm-project` implies that the submodule is there as well -- can you clarify what sources you were expecting to see?

**Comment by andrewchambers** [comment]
Ah thank you, I tried a rust-src link not a rustc-src link. Slightly confusing, I imagined rust would be less specific than rustc.

**Comment by andrewchambers** [comment]
@Mark-Simulacrum Note the tarball you linked is not in the manifests you linked.

**Comment by Mark-Simulacrum** [comment]
Yes, we don't include it in the manifests today -- I think that's probably "just a bug" -- we'd want to be careful to not add it as a rustup component if we do add it to manifests, though.

**Comment by XAMPPRocky** [comment]
This looks like this functionality would be easy to the mdbook plugin, however I don't know what the expected content to put in "Other Installation Methods". Which tarballs of which toolchains should be shown? What do we say about what the intended purpose of them is?

**Comment by andrewchambers** [comment]
Offline builds/distributions/other

**Comment by XAMPPRocky** [comment]
@andrewchambers Distributions & Package maintainers aren't something I believe are not in the manifest files.

**Comment by andrewchambers** [comment]
Sorry, I misread your question.

**Comment by ehuss** [comment]
I'm not really clear what this issue is asking for. It looks like the links at https://forge.rust-lang.org/infra/other-installation-methods.html#source-code contain direct links to the source tarballs with all the vendoring and submodules. Since this is quite old, I'm going to assume that is now resolved.
