### ISSUE TITLE
Internationalize the front page dates somehow

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust-forge#261]
Hello! This is not actually a big issue, but it's a little annoying. Since i and my friends are in a very different timezone (UTC+8), the actually release date like "September 26th 2019" always means September 27th to us in our local time zone :) So whenever there's a new release, questions like "Why is it not there yet?" is raised up again and again.

I wonder if something could be done here? Thank you!

**Comment by XAMPPRocky** [comment]
It now says `UTC` on the dates, which I think is the best we can do for now.
