### ISSUE TITLE
Cannot download rust src - broken link - stable only

### ISSUE THREAD

**Issue by hgabe** [rust-lang/rust-forge#263]
https://static.rust-lang.org/dist/rust-stable-src.tar.gz

every time I tried to download I get a not found error page

https://ibb.co/NKHL9Yw

**Comment by pietroalbini** [comment]
Hi! Just checked the contents of the website, and the correct URLs are:

```
https://static.rust-lang.org/dist/rust-src-{channel}.tar.gz
https://static.rust-lang.org/dist/rust-src-{channel}.tar.xz
```

Channel can be `beta`, `nightly` or a version number. Seems like `stable` isn't there though, I'll have to investigate a bit more on why it's missing.

**Comment by pietroalbini** [comment]
Ok no we never produced `rust-src-stable.tar.gz`s.

**Comment by cuviper** [comment]
There are two different source packages
- `rustc-{channel}-src.tar.*` is the complete source distribution for building the toolchain.
- `rust-std-{channel}.tar.*` provides the `rust-src` component for rustup. This just includes what's needed to build `std`, for use by `rls`, `xargo`, etc.

**Comment by hgabe** [comment]
I am using stable, the nightly version i has been added due to racer and I can't download the stable src for the RUST_SRC_PATH environment variable so it can be used to compile against it.

**Comment by hgabe** [comment]
can someone tell me how downloading beta and nightly works, but stable doesn't
