### ISSUE TITLE
404 for the page of Other Installation Methods.

### ISSUE THREAD

**Issue by cstffx** [rust-lang/rust-forge#284]
If you go to https://www.rust-lang.org/tools/install and scroll to 

Other installation methods

when you press LEARN MORE you will get an 404 error.

**Comment by bagasme** [comment]
I think rust-forge haven't been deployed yet?

**Comment by jonas-schievink** [comment]
There should be a redirect from the old link

**Comment by XAMPPRocky** [comment]
Redirect pages are generated, however they seem to be missing in `gh-pages` for some reason. Investigating.

**Comment by XAMPPRocky** [comment]
Seems to have been a caching issue on travis' side, closing as spurious.
