### ISSUE TITLE
Cargo (tag) 0.41.0 builds (and seems to work) fine on aarch64-pc-windows-msvc

### ISSUE THREAD

**Issue by harrisonmetz** [rust-lang/rust-forge#300]
The platform support for aarch64-pc-windows-msvc (for devices such as Microsoft Surface Pro X) seems to work with the 1.41. Cargo uses git2-rs, which uses libssh2 and that needs to be v0.2.14 or higher to build on windows (previous versions v0.2.13 had issue with the socket size).

It seems on the platform support for tier 2 only the `std` box is checked for this platform when the `cargo` box could be as well.

**Comment by Mark-Simulacrum** [comment]
The boxes are checked for the artifacts we publish (and as such guarantee, in some sense, their existence). We do not, I believe, publish Cargo for that target, so we cannot check the box even though it builds.

**Comment by harrisonmetz** [comment]
What does it take to publish binaries? Is that rust-forge, or another project? Thanks.

**Comment by Mark-Simulacrum** [comment]
rust-lang/rust, this repo is only for docs. But we probably don't have CI budget right now to publish Cargo binaries for more platforms.
