### ISSUE TITLE
Source binaries

### ISSUE THREAD

**Issue by dilyanpalauzov** [rust-lang/rust-forge#335]
https://forge.rust-lang.org/infra/other-installation-methods.html#source-code says

“Source code: Binaries + Signatures”

Source code is the opposite of binary.  Use other words, so that no contradictions appear.

**Comment by jonas-schievink** [comment]
Transferred to the right repo. Want to open a PR?

**Comment by dilyanpalauzov** [comment]
I do not want to open a PR, since I am not sure that the source code can compiled without implicitly downloadig binaries.

**Comment by jonas-schievink** [comment]
It cannot, as rustc is a bootstrapping compiler, but if the archives there really just contain binaries that shouldn't matter (it should still not say "source code")

**Comment by XAMPPRocky** [comment]
I believe the "Binaries" in "Binaries + Signatures" is referring to the tar file. Those files do contain the source code. I've changed it to "Archives" to help clarify that.
