### ISSUE TITLE
Windows scared of rust installer. Can the msi be signed?

### ISSUE THREAD

**Issue by emelens** [rust-lang/rust-forge#367]
![image](https://user-images.githubusercontent.com/18240627/83706764-3fe6cf80-a610-11ea-9f7b-deb6d832b095.png)

**Comment by kennytm** [comment]
This issue is tracked in rust-lang/rustup#1568.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! However this is a repository for the forge website not building rustup, so I’m going to close this issue. You can follow the rustup issue linked for more information on the issue.
