### ISSUE TITLE
broken link in src/libs/README.md

### ISSUE THREAD

**Issue by p-alik** [rust-lang/rust-forge#398]
The link  "Zulip and how the Rust community uses it." on [src/libs/README.md](https://github.com/rust-lang/rust-forge/blob/master/src/libs/README.md) has the target https://github.com/rust-lang/rust-forge/blob/master/chat/zulip.html, which doesn't exists.

Same issue on https://forge.rust-lang.org/libs/index.html

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Should be fixed now.
