### ISSUE TITLE
Other Installation Methods not getting processed for deployment

### ISSUE THREAD

**Issue by hexdreamer** [rust-lang/rust-forge#511]
This document: https://github.com/rust-lang/rust-forge/blob/master/src/infra/other-installation-methods.md
Deploys as: https://forge.rust-lang.org/infra/other-installation-methods.html

One can see that the placeholders under Standalone Installers and Source code are not being replaced with the real content. You just continue to see:

{{#installer_table}}
{{#source_code_table}}

**Comment by mrozekma** [comment]
Also `{{#rustup_init_list}}`

**Comment by mrozekma** [comment]
This appears in the CI builds:

```
error[E0599]: no method named `disable_built_in_roots` found for struct `TlsConnectorBuilder` in the current scope
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.1/src/async_impl/client.rs:218:25
    |
218 |                     tls.disable_built_in_roots(!config.tls_built_in_root_certs);
    |                         ^^^^^^^^^^^^^^^^^^^^^^ method not found in `TlsConnectorBuilder`

error: aborting due to previous error
```

Seems to be seanmonstar/reqwest#1181

**Comment by XAMPPRocky** [comment]
Thank you for your issue! This has been fixed this morning.
