### ISSUE TITLE
installer_table and source_code_table are not rendered

### ISSUE THREAD

**Issue by link2xt** [rust-lang/rust-forge#513]
At the bottom of https://forge.rust-lang.org/infra/other-installation-methods.html the text literally shows `{{#installer_table}}` and `{{#source_code_table}}`.

**Comment by link2xt** [comment]
Seems to be working again, closing the issue.

I have figured the link https://static.rust-lang.org/dist/rust-1.50.0-x86_64-unknown-linux-gnu.tar.gz out already without the page though :)

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I fixed it this morning.

**Comment by kellda** [comment]
Hi, the issue is there again
