### ISSUE TITLE
DOCS_RS_LOCAL_DOCKER_IMAGE seems to be depricated

### ISSUE THREAD

**Issue by Ayush1325** [rust-lang/rust-forge#586]
When using the default instructions to add packages for docs.rs, the instructions seem to contain the environment variable `DOCS_RS_LOCAL_DOCKER_IMAGE`. This however gives the following error:
```
env variable DOCS_RS_LOCAL_DOCKER_IMAGE is no longer accepted; use DOCSRS_DOCKER_IMAGE instead
```
I am going to open a pull request soon but just wanted to open the issue for information about this.

**Comment by ehuss** [comment]
Closing as I believe this has been resolved by #624.
