### ISSUE TITLE
Blacksmith directive not processed correctly

### ISSUE THREAD

**Issue by novedevo** [rust-lang/rust-forge#651]
[In src/infra/other-installation-methods.md](https://github.com/rust-lang/rust-forge/blob/dc026b033d022d10041b455c5f07611ead47899e/src/infra/other-installation-methods.md?plain=1#L76), on line 76, there is a directive for blacksmith ({{#rustup_init_list}}) that is left untouched in the rendered page at https://forge.rust-lang.org/infra/other-installation-methods.html. This also applies to the two following preprocessor directives.
![image](https://user-images.githubusercontent.com/20878868/193169245-d088207a-4a2a-4ff4-b5d7-e36a748f3158.png)

**Comment by ehuss** [comment]
Thanks for the report!  This is a duplicate of #649, and there is a fix up at #650.

**Comment by novedevo** [comment]
Thank you! Must have missed those, since they were already closed. Appreciate it.
