### ISSUE TITLE
Show the standalone installers for earlier releases (`FIXME`)

### ISSUE THREAD

**Issue by ojeda** [rust-lang/rust-forge#676]
While it is currently easy to figure out the URLs for older releases, it would be better to have a way to show the earlier releases somehow.

There is a `FIXME` comment about it in the docs:

https://github.com/rust-lang/rust-forge/blob/793249870cf7610ffe78dcb9c7acc7efdbbcc713/src/infra/other-installation-methods.md?plain=1#L99-L101

**Comment by yerke** [comment]
@ojeda Are you looking for a way to list installers just for stable channel or all channels? If we decide to show nightly, the list will be too long.

**Comment by ojeda** [comment]
For our use case, only stable releases (and I would imagine it is also the most important case for others too).

Thanks!

**Comment by yerke** [comment]
My WIP PR is here: https://github.com/rust-lang/rust-forge/pull/733
